### ISSUE TITLE
github actions workflow fails

### ISSUE THREAD

**Issue by flurin-conradin** [juntagrico/juntagrico-custom-sub#37]
Currenty, the ci workflow upon new commits fails. The command `django-admin.py makemigrations --noinput  coverage run -m manage test` fails as `django-admin.py` seems to have been [deprecated after django 4.0](https://docs.djangoproject.com/en/dev/internals/deprecation/#deprecation-removed-in-4-0).

**Comment by flurin-conradin** [comment]
@motu55 Do you mind if I have a look at this and does it make sense from your perspective?

**Comment by pascalfree** [comment]
On the main repo the test command has been updated.

https://github.com/juntagrico/juntagrico/blob/main/.github/workflows/juntagrico-ci.yml#L47

Maybe that also works here.

**Comment by flurin-conradin** [comment]
Thanks @motu55, I had a look there and added python version 3.10 which is being used by basimilch on heroku. I made a PR https://github.com/juntagrico/juntagrico-custom-sub/pull/38 Would if be OK for you to have a look? Thanks in advance!

**Comment by flurin-conradin** [comment]
Closed as https://github.com/juntagrico/juntagrico-custom-sub/pull/38 merged
